### PR TITLE
Allow Guzzle v5.x

### PR DESCRIPTION
**Pull request by oradwell**
Allow Guzzle v5.x

Had to change ResponseValidator::status() since in Guzzle v5 the status code is kept as integer.

### CODE REVIEW

**Comment by JoakimLofgren** [comment]
Thanks for the pull request.

Weird that the code coverage decreased.
Locally, when I run `composer run test` and open build/coverage/index.html it's at 100%.

**Comment by oradwell** [comment]
The files it reported with coverage change hasn't even been modified. Maybe it fixes itself if we run the build again.

**Comment by JoakimLofgren** [comment]
Yeah, seems to have been a hiccup with travis/coveralls.

**Comment by oradwell** [comment]
See #4 
I only casted `$httpStatus` to string

**Pull request closed without merging**
