### PR TITLE
update guzzle version

### PR DESCRIPTION
**Pull request by shivergard**
Increase guzzle version , so it can be loaded in Laravel 5

### CODE REVIEW

**Comment by keis** [comment]
Hi and thanks for the pull request.

I think it looks reasonable so :+1: from me.
ping @JoakimLofgren

**Comment by JoakimLofgren** [comment]
Could you update the lock file as well?
The tests are still running with 5.x version Guzzle.

And since it seems like Guzzle use semver you could put it as <7 so all 6.x versions are allowed.
E.g. http://semver.mwl.be/#?package=guzzlehttp%2Fguzzle&version=%3E%3D4.2%20%3C7&minimum-stability=stable

Considering how much Guzzle has changed between 5.x and 6.1.. it could be an idea to release this as 3.0. Anyone implicitly relying on Guzzle when using our SDK could get issues.

**Comment by bjora857** [comment]
Is this going to be merged anytime soon?

**Comment by rasmusbe** [comment]
please merge this, its breaking google php api client as well

**Comment by rockymontana** [comment]
Any day now... right? 😂

**Comment by rasmusbe** [comment]
Klarna is really maintaining their 💩 ...

**Comment by rockymontana** [comment]
Yeah... they're really spitting out new releases!
Now their library are breaking our codebase so that we can't upgrade to a current version of guzzle which is really crappy... 😞🙄

**Comment by sirn-se** [comment]
No, simply increasing version tolerance in composer.json won´t be enough. Guzzle 6.x is **not** compatible with 4.x/5.x.

Actually running the tests with Guzzle 6.x causes large amount of errors.

**Comment by 0x20h** [comment]
Closing this one. We are working on support for Guzzle 6 with PR #12, thanks for your support.

**Pull request closed without merging**
